# Generated by Django 2.1.2 on 2018-11-09 13:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('time_clock', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useractivity',
            options={'ordering': ['-timestamp'], 'verbose_name': '打卡记录', 'verbose_name_plural': '打卡记录'},
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='activity',
            field=models.CharField(choices=[('checkin', '签到'), ('checkout', '签出')], default='checkin', max_length=20, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='记录时间'),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
    ]
