# Generated by Django 2.1.2 on 2018-11-09 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_clock', '0002_auto_20181109_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractivity',
            name='activity_count',
            field=models.IntegerField(blank=True, default=0, verbose_name='操作次数'),
            preserve_default=False,
        ),
    ]
